### ISSUE TITLE
Cambio de RANKING.

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#10]
Nombres de "TATOS" Vietnamitas para insertar en la BBDD y que salgan las primeras. (Lo hago yo, CARLOS).

**Comment by CarlosHernando** [comment]
David, pregunta. Estoy con el tema del ranking, hay solo dos apps, que lo tienen, pero en vez de las coins ponen la pasta (más lógico). Y lo mas cañero es lo que tienen tap cash, con el user tracker (no sé si será real o no), echale un ojo! Y me dices como lo hacemos, si te mando diez nombres de por ahí con cantidades de coins, o de $...

**Comment by CarlosHernando** [comment]
oye lo de offline y online funciona seguro? Pablo se conecta y no le cambia el estado...

**Comment by CarlosHernando** [comment]
Ya vemos que podemos desde la base de datos añadir gente y coins nosotros...eso de momento...

**Comment by fappnatics** [comment]
Quitamos el marcador de online/offline

**Comment by fappnatics** [comment]
El ranking se limita a 10, TOP 10!!!

**Comment by CarlosHernando** [comment]
Usuarios mas falsos que judas incluidos

**Comment by fappnatics** [comment]
Lista limitada a 10 usuarios y quitada la imagen de Online/Offline.

**Comment by CarlosHernando** [comment]
Pues cerramos issue!se podría hacer algo más guapo como hablamos pero de momento así se queda!
