### ISSUE TITLE
PayOuts en la zona BENEFICIOS

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#11]
PayOuts: Paypal 5$ = 5500coins; Amazon 2$ = 2000coins ; Amazon 5$ = 4500coins.

Hay que remaquetar:

El contador de coins arriba. Debajo, una rejilla de 1x1 con 3 filas con el logo de Amazon, Paypal y cada uno tendrá su botón para solicitar el tipo de payout. No hay un botón al final. 

Hay que restarle los coins en cuanto solicite el cobro.

**Comment by CarlosHernando** [comment]
Mensajes que deberían saltar:
- Si no tienen coins para canjear y le pinchan en una opción: “you have no enough coins to get this gift”.
- Si hacen el payout de una gift card de Amazon: “it is your email address you would like to receive your gift card: xxxx@gmail.com” y mostrar el de gmail o dar la opción de cambiarlo.
- Si hacen el payout de pago en PayPal: “it is your email address linked to your PayPal account: xxxx@gmail.com” y mostrar el de gmail o dar la opción de cambiarlo.

Algo asi no david?como nos llegaría a la BBDD? Mira como debería hacerse!

**Comment by CarlosHernando** [comment]
SI es muy complicado david, que cuando llegue un payout se inicia un proceso manual y nosotros le contactamos, si es muy complicado lo anterior.

**Comment by fappnatics** [comment]
Ok, los mensajes no son complicados de hacer, es una causística sencilla. Los pagos actualmente os llegan a la BBDD a una tabla llamada TAB_PETICION_COBROS. Esta tabla habría que ampliarla con una columna más en el que se especifique el tipo de petición del usuario en base a los distintos GIFTS disponibles.

**Comment by CarlosHernando** [comment]
OJO!OJO!OJO! cambio de planes:

PayOuts: Paypal 5$ = 5000coins; Amazon 2$ = 2000coins ; Amazon 5$ = 5000coins.

Pero hay que dejar claro que si se hace el pago por PayPal el usuario debe pagar la fee de PayPal. Es decir, debemos incluir una nota bien clara y grande de que "PayPal withdraws/payouts do not include the PayPal fee, 3.4% + 0.30$, so around 0.47$ will be charged in your PayPal account"

ok?Dime si tienes dudas!

**Comment by fappnatics** [comment]
Únicamente me queda probar una secuencia completa, pero estaría hecha entera esta pantalla. Resta el saldo, actualiza el nuevo saldo, pide el correo PayPal, envía el correo de solicitud de cobro y avisa con un diálogo al usuario de que se ha realizado el pago.

**Comment by CarlosHernando** [comment]
Pues genial, nos dices cuando este máquina!

**Comment by fappnatics** [comment]
La página está lista, todo preparado para empezar las pruebas de este punto.

**Comment by CarlosHernando** [comment]
issue cerrada pues
