### ISSUE TITLE
Literales a cambiar.

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#12]
- El subtitulo de Beneficios pone "celebración"... WTF.
- El subtítulo de Ofertas pone "Invita a un amigo". (Resuelto in situ).
- El subtítulo de Clasificación debe ser algo como "Los más activos".

**Comment by fappnatics** [comment]
El subtitulo de Beneficios se ha cambiado por "Obten tu beneficio"
El subtítulo de Ofertas pone "Invita a un amigo". (Resuelto in situ).
El subtítulo de Clasificación se ha cambiado por "Los más activos".
