### ISSUE TITLE
Rediseño de la pagina principal.

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#14]
1- La aplicación arrancará en la lista de ofertas, que incluirá la imagen de instrucciones.
2- Quitar la sección Compartir, e incluir el perfil tal y como se indica en la issue correspondiente (fusionar perfil y compaertir, la información del referido).

**Comment by fappnatics** [comment]
![ofertas](https://cloud.githubusercontent.com/assets/10427412/7757353/e32c81e0-0001-11e5-8237-1e882d607189.png)
