### ISSUE TITLE
Crear las nuevas secciones.

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#15]
Crear las siguientes secciones;
- FAQ
- About Us
- Contact Us.

Ya te enviaré los contenidos.

**Comment by CarlosHernando** [comment]
Solo
- FAQ
- Contact US

**Comment by CarlosHernando** [comment]
Done, pero ahora falta que los textos estén bien. 

Los textos de About us y FAQ siguen sin estar bien. Lo acentos dan fallos en español y en la versión en inglés el apostrofe "´" (podemos cambiarlos, es decir no poner acentos y no poner apostrofes lo que digas)

**Comment by fappnatics** [comment]
Tal y como hemos hablado, yo he metido el cuezo y he creado 

FAQ
Contact US

Como me has dicho que lo deje, lo dejo, cerrando issue.

**Comment by CarlosHernando** [comment]
Ojo, se ha quedado, FAQ y About us (que incluye contact us)

¿Pero esta resuelto el tema de los caracteres especiales? Apostrofres y acentos?
