### ISSUE TITLE
Revisar el servicio de pagos.

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#16]
- Geenapp incluye postbacks a 0 por clicks (es una teoría). Hay que impedir que incluya ceros.
- En ocasiones el servicio no ha saltado hasta que no hemos reiniciado la aplicación.
- Al pulsar la notificación, te lleva a la aplicación pero no a una nueva, sino levantar la existente. Además tiene que descartar la notificación.

**Comment by fappnatics** [comment]
Únicamente falta revisar el último punto, de momento puede quedar así:
- He creado un script que se lanza cada vez que la aplicación se abre, y que borra los ceros de la tabla postback.
- El inicio de servicio se ha modificado, ahora si el servicio está funcionando, se mata y se vuelve a arrancar para intentar resolver el pronblema, pero es algo que prefiero que porbéis vosotros cuando estéis metidos en faena.

**Comment by CarlosHernando** [comment]
bueno, dejo la issue abierta y le damos una vuelta cuando mandes el apk y empecemos a generar clicks etc!
