### ISSUE TITLE
Duda Diseño

### ISSUE THREAD

**Issue by pablogrk** [fappnatics/CashMyAppsProject#17]
David una pregunta ¿los elementos de diseño los podemos modificar simplemente modificando las imágenes correspondientes?

He visto que hay carpetas de imágenes por aquí con diferentes tamaños/versiones. ¿Si se modifican luego se recompila el APK y listo?

Quizás para no darte el coñazo sería estupendo si nos puedes dar 2 indicaciones en plan, aquí están las imágenes, aquí los XML con el texto que se muestra, para que los podamos modificar y recompliar nosotros mismos para sacar upgrades en la app en materia de diseño/textos

Thanks!!

**Comment by fappnatics** [comment]
Supongo que te refieres al repositorio del código fuente. En principio así debería ser, si cambiáis alguna imagen se podría colgar ahí y después yo me descargo la imagen modificada y a partir de la próxima vez que simplemente depure ya haría uso de la nueva imagen... aunque me parece algo más complicado.

Si queréis cambiar alguna imagen, me lo decís, me las mandáis, y yo las cambio en el proyecto, y es el entorno de desarrollo que se encarga de actualizar el repositorio de GitHub, que realmente es el flujo normal de uso.

Saludos tíos!
