### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by pablogrk** [fappnatics/CashMyAppsProject#18]
David, ¿Podemos poner Google Analytics para Mobile Apps a funcionar?

Si creas una cuenta de Analytics y lo configuras comparte el acceso simplemente con pablo@pablogr.com y Carlos comparte tu correo de Gmail para compartirte el Analytics.

https://support.google.com/analytics/answer/3389142?hl=en (Cómo configurarlo).

Thanks

**Comment by CarlosHernando** [comment]
carloshernandoig@gmail

**Comment by fappnatics** [comment]
No lo he hecho nunca, he leído el manual que me habéis pasado, creo que quedará para lo último si no es inconveniente.

**Comment by pablogrk** [comment]
Ni te preocupes David, hay tiempo sin problemas
