### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#19]
David, he visto que la versión en inglés chana, pero hay una cosilla, el menú lateral no se traduce.

**Comment by CarlosHernando** [comment]
Todo lo demás si, igual no esta traducido, puedes mirarlo?

**Comment by fappnatics** [comment]
Es cierto, dejé fuera de la traducción las etiquetas del menú lateral en el XML que os pasé. HAremos una cosa, lo dejamos para el final porque hay que modificar las etiquetas del menú lateral, ¿ok?.

**Comment by CarlosHernando** [comment]
Bien, no problema. Mientras que no se te pase ;)!

**Comment by fappnatics** [comment]
En la próxima traducción, este error estará resuelto

**Comment by CarlosHernando** [comment]
pasamos para traducir ;)!

**Comment by CarlosHernando** [comment]
Te paso las cosillas que faltan por traducir:
- Sidebar cuando el móvil esta en inglés sigue apareciendo en Español. Y en vez de my account aparece "compártelo" (en la versión español si pone perfil).
- My account. Aparece en español tres palabras aparte de otras en inglés: Nombre, correo y modificar. Además cuando esta cargando sigue poniendo "Cargando datos de usuario..." en español.
- En la barra superior en la versión inglesa para el About us y el FAQ, lo pone en español, Nosotros: Acerca de nosotros y FAQ preguntas frecuentes.
- Cuando estas en la versión inglesa y metes el correo de PayPal, la confirmación esta en español, lo mismo cuando haces un payout, son imagenes que habría que traducir. 
- La opción de compartir esta genial, pero una cosa mal, es que si estas en la versión inglesa, cuando compartes el texto lo sigue poniendo en español: "descarga cashmaker y gana dinero".

Oye, quita lo de Aleman, que solo este en español e inglés que lo podemos controlar, ¿ok?.

**Comment by CarlosHernando** [comment]
Otra cosilla en la pantalla de payout enla versión en inglés esta en español "tu saldo" en lugar de "your coins" :)

**Comment by fappnatics** [comment]
Por lo que he podido repasar, todo hecho.

**Comment by CarlosHernando** [comment]
¿Si? de puta madre si quieres mañana le pegamos una vuelta!

**Comment by CarlosHernando** [comment]
Solo queda esta entonces!

Además cuando esta cargando sigue poniendo "Cargando datos de usuario..." en español. Que ponga "Loading profile"

**Comment by fappnatics** [comment]
Todo correcto confirmado!
