### ISSUE TITLE
Pantalla inicial

### ISSUE THREAD

**Issue by pablogrk** [fappnatics/CashMyAppsProject#2]
Al entrar, ¿la gente sabe lo que tiene que hacer? Ej. Pulsar arriba a la izquierda.

Nada más entrar tiempo de carga perfect.

En Información de la cuenta “Pulsa arriba a la derecha y selecciona ofertas para comenzar a descargar y ganar!

**Comment by fappnatics** [comment]
Ok, unas instrucciones ¿que se muestren solo la primera vez quizá? ¿o que esté siempre? que indique unas instrucciones simples para ayudar a comenzar a usar la aplicación.

**Comment by fappnatics** [comment]
Estoy viendo con Carlos este punto y revisando la app Takatap y veo claro que hay que incluir una pequeña sección de instrucciones en la pantalla principal.
![takatap_instructions](https://cloud.githubusercontent.com/assets/10427412/7679389/8065eeea-fd5c-11e4-896d-ea6c950a5057.png)

**Comment by pablogrk** [comment]
Eso es, quizás cargar directamente como hacen en Takatap con esa pequeña explicación arriba estaría genial.

**Comment by fappnatics** [comment]
En principio está hecho, a falta de que me mandéis la imagen para poner las instrucciones, la aplicación ya arranca en la zona de ofertas. 

Habrá que volver a hacer pruebas de tiempo de arranque, porque la pestaña de las ofertas tiene mucha más carga que la anterior con la información del usuario, que estaba hecha más o menos por eso, para una entrada ligera. Parece que no tengo pantallas negras, pero con conexiones muy lentas podrían aparecer. Ojo con esto porque con la cantidad de carga que tiene será bastante difícil optimizar el arranque.

**Comment by fappnatics** [comment]
Esto está cerrado, se han añadido pié y cabecera a la lista de apps con las instrucciones,

**Comment by CarlosHernando** [comment]
vale cierro issue y ya veremos el tiempo de carga y demás de como optimizar la app!
