### ISSUE TITLE
Opción compartir

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#22]
David, ya que hemos subido la app al play store. Deberiamos actualizar la opcion compartir, solo muestra unete a cashmaker, deberia venir el link del play store y el logo al menos no?

**Comment by fappnatics** [comment]
Ya estaba hablado si recuerdas. Primero había que subir la app al play store y hacer la web para tener algo que compartir. La siguiente versión que os pase irá con contenido en el compartir.

**Comment by fappnatics** [comment]
Solucionado a falta de revisión.

**Comment by CarlosHernando** [comment]
Vale entonces cierro esta issue!
