### ISSUE TITLE
Error para algunas versiones moviles

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#24]
David, como ya sabemos en mi móvil no funciona la app, pero ayer con dos amigos ví que en ninguno de sus dos móviles no funcionaba tampoco, le tome una foto para que veas la versión que es.
Me preocupa mucho este tema. La app carga hasta la pantalla de introducir el usuario, pero cuando va a cargar el listado de ofertas pantallazo negro, y ya no carga más veces. Como crees que se podría depurar esto o que podríamos hacer?
![2015-05-28 21 20 40](https://cloud.githubusercontent.com/assets/12494850/7879929/cb0b4830-05ec-11e5-8fee-72bf431460f4.jpg)

**Comment by CarlosHernando** [comment]
Ah los dos móviles eran versiones mas actuales que la mía.

**Comment by fappnatics** [comment]
Es un Galaxy Core... supongo que están en KitKat. Pues muy jodido depurar esto porque cuando lo hice con el tuyo Android Studio directamente se desconectaba y la aplicación moría. No es culpa realmente de la App, es alguna peculiaridad que tienen vuestros terminales y su sistema los que impiden que la aplicación funcione correctamente... y es que Android es así... a mí pasaba lo mismo con la aplicación de Facebook... cuando actualicé el móvil empezó a funcionar sin problema. Apostaría lo que fuera a que si te flasheo el móvil y te pongo.. por ejemplo, CyanogenMod (una ROM para muchos móviles), la aplicación comienza a funcionar. Para intentar cualquier cosa, tendría que tener el terminal que produce el fallo exactamente, porque reproduje con exactitud las características y versión de ANdroid en un emulador para PC y arrancaba sin problema la aplicación... y es que es muy muy complicado de tracear, ya que como ves no produce un error... se queda en negro y se cuelga.

No obstante, yo no me preocuparía porque aunque hayas encontrado contigo 3 que hace lo mismo, no será ni una parte significativa del total... a mí me va, en la Nexus 7 de Lydia va, en su móvil también, a Pablo le funciona, y a tu hermano, a tu madre... etc, etc... Esta noche lo voy a probar en un BQ y un LG G2... para comprobar que no hace lo mismo.

Lo iremos viendo de todos modos.

**Comment by CarlosHernando** [comment]
Claro eso es lo que vamos a hacer...probar y probar y a ver...yo si veo alguien que tenga android lo pruebo y ya esta. Y seguimos viendo...

**Comment by CarlosHernando** [comment]
David lo que te decía ayer en el S3 galaxy mini 4.1.2. tampoco chanaba así como en el sony experia 4.3.  para ir seguir probando modelos...

**Comment by fappnatics** [comment]
Para solucionar el bug, necesito encontrar y disponer de uno de los terminales donde se esté produciendo este error... voy a tratar de reproducirlo en el de alguien conocido con el que pueda quedar para que me lo preste y depurarlo en la Surface. Insisto, es un problema del sistema, no de la app... es importante, porque cuando yo intenté depurarla en tu móvil, Carlos, el depurador del entorno de desarrollo directamente se desconectaba... y sin error no hay manera de arreglarlo. Espero, y puede ser que sea, que esté relacionado con el tema de la localización que creo que he terminado de afinar... en la próxima versión de la APP que os distribuya lo comprobamos. 

No obstante, a ver si tenemos algún dia tiempo, porque si me dejas que te flashee el móvil, te aseguro que la app te funciona.

**Comment by CarlosHernando** [comment]
Vale, vamos a lanzar ese apk nuevo y vemos? Sino busco a alguien que no le vaya alli y lo puedes probar!

**Comment by CarlosHernando** [comment]
Según revisión de estos días en PlayStore cerramos esta issue.
