### ISSUE TITLE
Zona PayOut no se ve bien el saldo. 

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#27]
![no se ve el saldo 2](https://cloud.githubusercontent.com/assets/12494850/8706443/9e1ba008-2b27-11e5-872d-53725c2e928d.png)
![no se ve el saldo](https://cloud.githubusercontent.com/assets/12494850/8706444/9e1eb360-2b27-11e5-9dde-a94a3eb63111.png)

**Comment by fappnatics** [comment]
Remaquetada, si hay cualquier porblema tomaré otras medidas....

**Comment by CarlosHernando** [comment]
vale la dejamos abierta, la probamos en los móviles de pablo y mío con el nuevo apk y ya la cierro...
