### ISSUE TITLE
En el sidebar, hay veces que pone XXX coins, pero otras pone solo el número

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#28]
![no se ve la palabra coins](https://cloud.githubusercontent.com/assets/12494850/8706456/b83c3132-2b27-11e5-8a1e-f7a534be7027.png)

**Comment by fappnatics** [comment]
Está resuelta. Al hacer los payouts actualizo las coins de la barra... pero olvidé ponerle el " COINS". Ya aparece siempre.

**Comment by CarlosHernando** [comment]
Cerramos issue entonces!

Vamossss!
