### ISSUE TITLE
Opción referir a un amigo

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#29]
Cuando metemos el código amigo se detiene la app, tanto si lo hacemos el uno al otro como el otro al uno

**Comment by fappnatics** [comment]
Ya no se detiene, encontré el error pero actualmente estoy atascado en un error que resolveré un poco más alante... voy a ir solventando otras issues porque ya le he dedicado mucho tiempo a esta.

**Comment by CarlosHernando** [comment]
OKey pero hay que dejarla finiquitada para el próximo apk, vale? Thanks!

**Comment by fappnatics** [comment]
Correcto!Funciona!
