### ISSUE TITLE
Zona COMPÁRTELO

### ISSUE THREAD

**Issue by pablogrk** [fappnatics/CashMyAppsProject#3]
Confuso ¿Para qué sirve?

**Comment by fappnatics** [comment]
Realmente tiene razón. En principio el objetivo era compartir,  pero realmente perdió su relevancia cuando incluí el icono de compartir en la barra superior. Realmente sirve para poner el referido, una vez incluido esa sección es inútil.

**Comment by CarlosHernando** [comment]
Quitar la opción de "compártelo" por una de profile para así también que los lerdos se den cuenta y no tengan que pinchar en la cabecera. Debe incluir los datos de la cuenta más la opción de ser referido.
