### ISSUE TITLE
Cálculo coins en los Payouts

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#30]
Payout. Pablo tenía 3.482 coins, salía solo para hacer 2.000 de Amazon (eso genial funciona bien), lo he hecho, y sale de resultado -518 coins. La opción de Amazon de ha quitado (genial).  No te preocupes mucho porque mirando en  la tabla de usuarios de PHP pone que tiene en total 1402, menos 2.000, seria -598, no esta bien el calculo, y entiendo que en el algún momento se toco el PHP y se le puso manualmente más coins tal vez. El email ha llegado dos veces eso si, y en la tabla PHP de peticiones de cobro aparece como dos veces realizado el payout, no se porque se ha duplicado. ¿Puedes revisar todo esto un poco?.

**Comment by fappnatics** [comment]
Acabo de hacer una prueba con mi usuario, con las mismas COINS que tenía Pablo, las 3482, y haciendo el PayOut de Amazon 2$, mi resto ha sido 1482... no sé si ha habido algún porblema en algún momento por haber tocado la base de datos como quien dice "a la vez"... (la BBDD a veces tarda un poco en refrescarse), pero es una operación muy sencilla... voy a volver a hacer la prueba, y hacedla vosotros de nuevo también, por favor, porque creo que eso ha sido un problema de la BBDD al ser modificada en un momento dado.

**Comment by CarlosHernando** [comment]
Ahora mismo lo hago...quizas el problema sea que hay mas coins actuales que en total david!Voy a ello!

**Comment by CarlosHernando** [comment]
Nada igual...y otro fallo macho!hago un payout de Amazon y me sale una imagen de PayPal, te adjunto pantallazo. 
![screenshot_2015-07-17-15-35-15](https://cloud.githubusercontent.com/assets/12494850/8749511/f72c23ac-2c99-11e5-9916-9eeaba00ba87.png)

**Comment by CarlosHernando** [comment]
Otra cosa, puedes verificar que la pantalla que sale en tantas horas se procesara tu pedido etc, esta también para la versión en inglés, please?

**Comment by fappnatics** [comment]
Es un poco inverosímil... por qué con tu usuario hace eso y con el mío no... yo estoy haciéndolo y va perfecto. 

En cuanto a lo que me acabo de comentar de que aparece lo del diálogo de PayPal con el pago Amazon... es lo que tiene el copia-pega... voy a quitarlo, jejejej.

**Comment by fappnatics** [comment]
El mensaje que comentas está traducido y disponible en inglés.

**Comment by CarlosHernando** [comment]
pues creo david que pasa porque no esta bien el total de las coins!hacemos una cosa? me pones a mi mas coins y lo pruebo yo...perfecto a las otras dos preguntas!oye más...en la tabla de cobros aparece siempre dos veces cuando se hace una solicitud! Pantallazo:
![tabla cobros](https://cloud.githubusercontent.com/assets/12494850/8749767/992fc540-2c9b-11e5-9cdd-c9b826f2732c.JPG)

Lo podriamos apañar? y como editar el N y poner un Y? en la tabla? me parece que no esta habilitado para editar!

**Comment by CarlosHernando** [comment]
Le ponemos otra columna?

**Comment by CarlosHernando** [comment]
Ole tu polla, ahora a calculado bien las coins del withdraw, solo ha llegado un correo, y solo aparece una vez en el PHP. OLE! Ademas he visto que esta en ingles para la version inglesa. MIra estas cosillas y cerramos esta issue!
- Lo que te preguntaba de como cambiar el N por Y en el PHP manualmente. 
- La imagen de PayPal quitala de Amazon y que nos llegue el correo de gmail de los usuarios cuando hagan withdraws de Amazon no?. 
- La imagen que aparece para el pago de PayPal esta en ingles? SIno habría que hacerla...

Una ultima cosa ponme otros 2000 coins que pruebe si con el withdraw de 5$ de PayPal nos llega el correo que ponga en ese momento al payout@cashmakertheapp.com. please ;)!

Venga que despegamos!

**Comment by CarlosHernando** [comment]
Bueno la comprobación que quedaba por hacer aquí ha fallado, abro otra issue, pero dejamos esta abierta ara el resto de cosillas que hay en ella...

**Comment by fappnatics** [comment]
Qué ha fallado exactamente? yo llevo toda la tarde de pruebas y me funciona correctamente... ?qué issue has abierto para este tema?

**Comment by CarlosHernando** [comment]
MIra estas cosillas y cerramos esta issue!

Lo que te preguntaba de como cambiar el N por Y en el PHP manualmente.
La imagen de PayPal quitala de Amazon y que nos llegue el correo de gmail de los usuarios cuando hagan withdraws de Amazon no?.
La imagen que aparece para el pago de PayPal esta en ingles? SIno habría que hacerla...

**Comment by CarlosHernando** [comment]
Dime sino lo tienes claro ok?
