### ISSUE TITLE
PayPal Gift 5$

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#31]
Dos cosas: 
- Cuando haces un payout de 5$ y pones el correo electrónico de PayPal a nosotros al email nos sigue llegando el mismo de gmail...podríamos mirar en la tabla de usuarios para ver si ha puesto uno de PayPal o incluso escribirle para ver si esta todo ok, pero lo suyo es que aquí vinieras indicado...

![paypal gift 5](https://cloud.githubusercontent.com/assets/12494850/8775749/03dce2e4-2ee3-11e5-9112-5d0a36c543e8.JPG)
- Cuando haces el PayOut de PayPal con la versión inglesa la pantalla de confirmación sigue apareciendo en español:

![screenshot_2015-07-20-13-15-59](https://cloud.githubusercontent.com/assets/12494850/8775764/2a0d9328-2ee3-11e5-8357-2fa102a2c5a9.png)

**Comment by CarlosHernando** [comment]
Me acabo de dar cuenta que pone también "tu saldo" En vez de "your coins"

**Comment by CarlosHernando** [comment]
Las dos últimas issues están también especificadas en otras issues abiertas!

**Comment by fappnatics** [comment]
Resueltas las incidencias de literales... la del correo, entiendo que si pide paypal sería indicar el correo PayPal en el mismo mensaje para no tener que ir a mirarlo a la tabla. Luego lo implemento y probamos a ver.

**Comment by fappnatics** [comment]
Finiquitado, ahora, cuando recibáis una petición de cobro PayPal, en el mismo correo recibiréis tanto el correo de usuario como el de PayPal.

**Comment by CarlosHernando** [comment]
cerramos jeje!!
