### ISSUE TITLE
Cambiar textos en al about us

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#32]
David, esto lo hacemos nosotros y luego si quieres lo coges, son dos chorradas...

<img width="434" alt="better english" src="https://cloud.githubusercontent.com/assets/12494850/8776162/ec0db982-2ee6-11e5-9ff9-8695204efef0.png">

**Comment by CarlosHernando** [comment]
A ver los textos para que los copies y los pegues...

3rd paragraph: "All you need to do is install the apps from the list of available applications, run them on your mobile device, and then we will automatically put the coins into your CashMaker account".

4rd paragraph: "Apart from obtaining coins by installing free apps, you can also get unlimited coins by inviting your friends. You can share CashMaker as many times as you want to start making serious pocket money from home. Is there any faster way of making money?"

**Comment by CarlosHernando** [comment]
Vale cambia esto en la versión inglesa. Y, ¡OJO! tanto en inglés como en español añade al final del about us:

CONTACTO

Si tienes cualquier consulta, te gustaría compartir alguna idea o darnos tu valoración, no dudes en contactarnos mediante: info@cashmakertheapp.com 

CONTACT

If you have any queries, you would like to provide suggestions or feedback, please do not hesitate to contact us at: info@cashmakertheapp.com

**Comment by CarlosHernando** [comment]
Pone: What is CashMaker? y Obtain your rewards. Pues pon otras sección al final que sea Contacto / Contact y las dos frases cada una en su idioma!

**Comment by fappnatics** [comment]
Modificados los textos del HTML en ambos idiomas. Cierro la issue.
