### ISSUE TITLE
Apostrofe en las descripciones de las App en Inglés

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#33]
A parte de que da error en el FAQ y en About Us, también da en la descripción de las apps en inglés. Estoy realmente es un pijotada pero si a raíz de lo otro se puede solventar también sin esfuerzo pues genial

<img width="474" alt="fallo apostrofe" src="https://cloud.githubusercontent.com/assets/12494850/8776387/964d04b0-2ee8-11e5-8e3e-39d5c0c81cb7.png">

**Comment by CarlosHernando** [comment]
Mira David si no hay punto en la descripción obviamente no lo corta, pero ande y que le follen jeje.

**Comment by fappnatics** [comment]
Es cierto.. pero si no tiene puntos en frases tan largas es que está mal redactado. Aparte, yo puedo utilizar más métodos para cortar las descripciones.... como contar 6 espacios y terminar con puntos suspensivos... pero en ese supuesto también nos sacarían la pega de que la frase no termina en un punto coherente... realmente lo que vosotros digáis.

**Comment by CarlosHernando** [comment]
No no que le follen a esta issue! lo uníco lo de los apostrofes se puede hacer algo??sino que le den por culo y se quede así la issue también!

**Comment by fappnatics** [comment]
Falta quitar los apostrofes del FAQ!

**Comment by fappnatics** [comment]
Terminada!
