### ISSUE TITLE
Zona VER OFERTAS

### ISSUE THREAD

**Issue by pablogrk** [fappnatics/CashMyAppsProject#4]
He descargado y no me ha sumado los 3 coins de 2 apps
He revisado en Geenapp y para Irlanda no aparece

**Comment by fappnatics** [comment]
¿no hay mercado para Irlanda? Cuando esa parte estaba en desarrollo comprobamos el market de Irlanda y si devolvía aplicaciones. De esto necesito más datos para ver qué está pasando.

**Comment by pablogrk** [comment]
Sí perdona, que me he explicado fatal.

Para Irlanda había 3 apps, me he descargado 2 de ellas (con una me saltaba un error de mi red móvil y no cargaba la URL.. cosa rara) y luego ya una vez instaladas no se ha generado ni el aumento de coins ni en Geenapp ha contado la instalación..

Ni idea que ha pasado.

Thanks!

**Comment by fappnatics** [comment]
También me ha pasado a mi alguna vez. Muchas veces es error de geenapp, que deja la oferta dada de alta y ya ha caducado... en muchas ocasiones se queda en una página intermedia y no para adelante ni para tras. Lo primero que habría que hacer seria tracear una instalación manual, es decir, componer el link y hacerla a mano desde el navegador para ver si eso lleva a algún lado, no descarto tener que poner algún soporte a geenapp porque non contabiliza algunas instalaciones. Voy a probar yo desde España alguna a ver si lo hace.

**Comment by pablogrk** [comment]
Ok perfecto, ni te preocupes entonces, estoy ya lo iremos viendo a medida que vamos lidiando con los useres reales a ver como evoluciona.

Thanks!
