### ISSUE TITLE
Zona OBTENER BENEFICIOS

### ISSUE THREAD

**Issue by pablogrk** [fappnatics/CashMyAppsProject#5]
¿A dónde van los emails de “obtener mis beneficios”?
En lugar de en logo grande en ese espacio meter una imagen con instrucciones. “Puedes solicitar cobro al tener XXX coins” te enviaremos un email con las opciones que tienes a tu disposición (PayPal Amazon Gift Card…)

**Comment by fappnatics** [comment]
Me están llegando a mí, no hay problema porque se define en el código php del fichero que envía los mails.

**Comment by fappnatics** [comment]
En cuanto a la imagen, soy consciente de que era provisional, cuando queráis pactamos el diseño de lo que debería mostrar en esa parte.

**Comment by CarlosHernando** [comment]
Pablo, hazte una cuenta de correo para comunicaciones como petición de cobros... algo así como cobros@cashmaker.com o lo que tú veas. Así David la incluye en el PHP que envía los correos y podréis ver las peticiones en la bandeja.

**Comment by CarlosHernando** [comment]
payout@cashmakertheapp.com Hazlo David y cierra la incidencia, y hacemos una prueba!
