### ISSUE TITLE
Texto ofertas apps

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#6]
Que la extensión del texto descriptivo vaya hasta el primer punto.

**Comment by fappnatics** [comment]
Solucionado, si el texto contiene un punto, cortamos hasta el punto, si no lo tiene no hago nada porque si intento hacer cualquier manipulación programáticamente de un texto que no contiene lo que busco, da un error y se cierra la aplicación, pero me parece que ha quedado muy bien.

![device-2015-05-18-192244](https://cloud.githubusercontent.com/assets/10427412/7686064/6b83f9ea-fd93-11e4-9eb2-acb48626a38d.png)
