### ISSUE TITLE
Revisar cálculo de las COINS

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#7]
Las COINS se calculan de la siguiente forma:

(PPI \* 0.2) truncar a 2 decimales, de manera que las coins quedan redondas, el mínimo pago son 10 coins.

**Comment by fappnatics** [comment]
Una pregunta con esto... (Carlos, no te rías).... ejemplo práctico:
0,21 \* 0,2 = 0,042 -> Redondeado a 2 decimales es 0,04, ahora x100 son 4... ¿40 coins? Es que prefiero concretar esto y ser el descojone generalizado, a meterlo otra vez mal...

**Comment by CarlosHernando** [comment]
Las pruebas que acabo de hacer salen bien, ahora solo falta que las sume bien que con la putada de Geenapp no sabemos si se hace bien o no...

**Comment by fappnatics** [comment]
¿Qué consideraciones hay que tomar para esta nueva situación? Por cerrar la issue.

**Comment by CarlosHernando** [comment]
Pues de momento nada...porque el hijo puta de geenapp no funciona, sería simplemente comprobar que suma bien las coins que se descargan...tendremos que probar con otro proveedor al final...¿crees que funciona bien el sumatorio de las coins? se supone que geenapp va a funcionar bien en un tiempo asíque lo utilizaremos...por eso quería verificar esto!
