### ISSUE TITLE
Diálogo de salida.

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#8]
El logo que muestra es el antiguo, poner el nuevo en el que el nombre es CashMaker.

**Comment by CarlosHernando** [comment]
Solucionado, he añadido el nuevo logo tanto con fondo negro como transparente. El transparente es el que se ha colocado en el diálogo.
![device-2015-05-18-184820](https://cloud.githubusercontent.com/assets/12494850/7685438/9be3b986-fd8e-11e4-91a2-77548d55f3d5.png)

**Comment by fappnatics** [comment]
Solucionado. He incluido tanto el logo con fondo blanco como transparente. El de fondo transparente es el que va en el diálogo de salida.
![device-2015-05-18-184820](https://cloud.githubusercontent.com/assets/10427412/7685490/fbbe5802-fd8e-11e4-816f-7009fea6b6e3.png)
