### ISSUE TITLE
Error al girar pantalla.

### ISSUE THREAD

**Issue by CarlosHernando** [fappnatics/CashMyAppsProject#9]
Al girar la pantalla se produce un FC (ForceClose) y se cierra la app.

**Comment by fappnatics** [comment]
Solucionado. Se bloquea la orientación de la pantalla a "PORTAIT" siempre. No tiene sentido permitir que se haga en apaisado a no ser que en las tablets de 10" nos represente un problema (normalmente las aplicaciones no se usan con la tablet de ese tamaño de pié).
